name: weirdhost-auto-add-time
on:
  schedule:
    - cron: '0 19 * * *'  # 每天 UTC 19 点执行（北京时间 3:00），按需调整
  workflow_dispatch:      # 支持手动触发

jobs:
  add_time:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || pip install playwright aiohttp
          # Install Playwright browsers (with necessary deps)
          playwright install --with-deps chromium

      - name: Run weirdhost-auto
        env:
          # 优先 Cookie 登录（可选）
          REMEMBER_WEB_COOKIE: ${{ secrets.REMEMBER_WEB_COOKIE }}           # optional: cookie value
          REMEMBER_WEB_COOKIE_NAME: ${{ secrets.REMEMBER_WEB_COOKIE_NAME }} # optional: cookie name, default 'remember_web'
          # 回退登录用的邮箱/密码（当 cookie 无效时使用）
          PTERODACTYL_EMAIL: ${{ secrets.PTERODACTYL_EMAIL }}
          PTERODACTYL_PASSWORD: ${{ secrets.PTERODACTYL_PASSWORD }}
          # 目标服务器（可选，脚本有默认值）
          SERVER_URL: ${{ secrets.SERVER_URL }}
          # Telegram 通知
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
          # 若将来使用打码服务，可在此加入 API key
          # TWOCAPTCHA_API_KEY: ${{ secrets.TWOCAPTCHA_API_KEY }}
        run: |
          python main.py
